FROM httpd:2.4

RUN echo "deb http://de.archive.ubuntu.com/ubuntu/ bionic main" >> /etc/apt/sources.list && \
		  apt-get update && apt-get install -y apache2 && \
		  apt-get install -y apache2-utils && \
		  apt-get install -y mysql-server

RUN apt-get update && apt-get install -y apache2 && \
		  apt-get install -y apache2-utils

EXPOSE 80

COPY ./web/ /usr/local/apache2/htdocs/

#ENTRYPOINT ["apache2ctl"]

#CMD ["-DFOREGROUND"]