name: CSEC380Project Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker-compose -f apache_web_server/docker-compose.yml up --build -d --tag csec380project:$(date + %s)
